### ISSUE TITLE
crashes in 1.16.2 when press the 'perspective' button

### ISSUE THREAD

**Issue by RodePapon** [BackportProjectMC/PerspectiveModRedux#3] opened 2020-09-03 18:05 UTC
java.lang.NoSuchFieldError: field_1850
    at pm.c7.perspective.PerspectiveMod.lambda$onInitializeClient$0(PerspectiveMod.java:72)

crash-report:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 3/09/20 19:41
Description: Unexpected error

java.lang.NoSuchFieldError: field_1850
	at pm.c7.perspective.PerspectiveMod.lambda$onInitializeClient$0(PerspectiveMod.java:72)
	at net.fabricmc.fabric.impl.event.lifecycle.client.LegacyClientEventInvokers.lambda$onInitializeClient$0(LegacyClientEventInvokers.java:29)
	at net.minecraft.class_310.handler$zba000$onEndTick(class_310.java:3326)
	at net.minecraft.class_310.method_1574(class_310.java:1577)
	at net.minecraft.class_310.method_1523(class_310.java:996)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at pm.c7.perspective.PerspectiveMod.lambda$onInitializeClient$0(PerspectiveMod.java:72)
	at net.fabricmc.fabric.impl.event.lifecycle.client.LegacyClientEventInvokers.lambda$onInitializeClient$0(LegacyClientEventInvokers.java:29)
	at net.minecraft.class_310.handler$zba000$onEndTick(class_310.java:3326)

-- Affected level --
Details:
	All players: 31 total; [class_746['RodePapon'/23134, l='ClientLevel', x=-217.50, y=14.00, z=-188.50], class_745['xKarnemelk'/22276, l='ClientLevel', x=-210.50, y=14.00, z=-191.50], class_745['Uchiha_Itachi__'/4626, l='ClientLevel', x=-218.50, y=14.20, z=-191.50], class_745['koraypro'/9919, l='ClientLevel', x=-217.50, y=14.00, z=-191.50], class_745['RomijnO'/20955, l='ClientLevel', x=-211.50, y=14.00, z=-190.50], class_745['§r'/615, l='ClientLevel', x=-227.50, y=12.00, z=-179.50], class_745['5QP'/13611, l='ClientLevel', x=-211.50, y=14.00, z=-192.50], class_745['§r'/622, l='ClientLevel', x=-201.50, y=12.00, z=-179.50], class_745['Reaperreddd'/21264, l='ClientLevel', x=-213.86, y=11.00, z=-174.48], class_745['Kat_stuf'/18089, l='ClientLevel', x=-216.61, y=11.00, z=-168.65], class_745['Nicolas525'/4625, l='ClientLevel', x=-232.53, y=12.00, z=-172.76], class_745['§r'/113, l='ClientLevel', x=-230.50, y=12.50, z=-160.50], class_745['CharlieMel'/22574, l='ClientLevel', x=-227.10, y=11.00, z=-163.57], class_745['§r'/604, l='ClientLevel', x=-198.50, y=12.50, z=-160.50], class_745['§r'/608, l='ClientLevel', x=-214.50, y=12.50, z=-157.50], class_745['§r'/97, l='ClientLevel', x=-218.50, y=12.50, z=-157.50], class_745['§r'/101, l='ClientLevel', x=-210.50, y=12.50, z=-157.50], class_745['§r'/109, l='ClientLevel', x=-222.50, y=12.50, z=-158.50], class_745['§r'/121, l='ClientLevel', x=-226.50, y=12.50, z=-159.50], class_745['Adelaida'/21718, l='ClientLevel', x=-174.09, y=14.08, z=-152.43], class_745['§r'/105, l='ClientLevel', x=-206.50, y=12.50, z=-158.50], class_745['§r'/117, l='ClientLevel', x=-202.50, y=12.50, z=-159.50], class_745['Varggo'/23465, l='ClientLevel', x=-208.28, y=12.00, z=-160.94], class_745['SweetMONSTER64'/23135, l='ClientLevel', x=-196.87, y=12.00, z=-174.35], class_745['SenseiFrost'/23703, l='ClientLevel', x=-220.74, y=11.00, z=-164.02], class_745['iCasinoDR'/23760, l='ClientLevel', x=-211.70, y=14.59, z=-184.79], class_745['Matiashu5'/23763, l='ClientLevel', x=-215.50, y=14.00, z=-188.50], class_745['NingaTurtlek3'/23874, l='ClientLevel', x=-210.19, y=11.45, z=-170.24], class_745['Cigar7'/23931, l='ClientLevel', x=-218.50, y=14.00, z=-187.50], class_745['felix5888'/22220, l='ClientLevel', x=-222.49, y=11.52, z=-161.08], class_745['dietherGamingYT'/23991, l='ClientLevel', x=-215.50, y=14.20, z=-187.50]]
	Chunk stats: Client Chunk Cache: 5041, 373
	Level dimension: minecraft:overworld
	Level spawn location: World: (-999999,575,-999999), Chunk: (at 1,35,1 in -62500,-62500; contains blocks -1000000,0,-1000000 to -999985,255,-999985), Region: (-1954,-1954; contains chunks -62528,-62528 to -62497,-62497, blocks -1000448,0,-1000448 to -999937,255,-999937)
	Level time: 1630249515 game time, 1637692000 day time
	Server brand: CubeCraft
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2183)
	at net.minecraft.class_310.method_1514(class_310.java:679)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), 
	Memory: 434738952 bytes (414 MB) / 1749024768 bytes (1668 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.4.0
		fabric: Fabric API 0.19.0+build.398-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5fa
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+fac8f3664e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.6.0+e81ec80b4e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+ba4afa574e
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a704e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.3+e5d3217f4e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+5d32f5834e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.10+e5d3217f4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.2.0+fc24ff244e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.9+e5d3217f4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.0+516ece7c4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.2+build.206
		minecraft: Minecraft 1.16.2
		perspectivemod: Perspective Mod Redux 0.0.4
		replaymod: Replay Mod 1.16.2-2.4.3
	Launched Version: 1.16.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 620 GL version 4.6.0 - Build 26.20.100.7926, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

**Comment by Cynosphere** [comment] 2020-09-03 19:08
duplicate of #2

**Closed as completed by Cynosphere** 2020-09-03 19:08 UTC
Labels: duplicate
